### PR TITLE
Fix geolocationAvailable

### PR DESCRIPTION
**Pull request by dylex**
If either (not both) navigator or navigator.geolocation are undefined, it's not available. (The whole thing could probably be simplified to `$window.navigator && $window.navigator.geolocation`.)

This hopefully fixes a bug that's been annoying me for a while where the branch location pages (like https://www.nypl.org/locations/ottendorfer) just show the unsubstituted templates (`{{location.name}} {{location.street_address}}`) and throws an exception:

```
[Error] Error: undefined is not an object (evaluating 'b.navigator.geolocation.getCurrentPosition') angular.js:8596
https://www.nypl.org/locations/dist/locinator.min.js:10:20413
https://www.nypl.org/locations/dist/locinator.min.js:10:30701
c@https://www.nypl.org/locations/dist/locinator.min.js:10:30821
instantiate@https://d2znry4lg8s0tq.cloudfront.net/angular/angular/1.3.15/angular.min.js:36:433
https://d2znry4lg8s0tq.cloudfront.net/angular/angular/1.3.15/angular.min.js:76:60
https://d2znry4lg8s0tq.cloudfront.net/angular/ui-router/0.2.13/angular-ui-router.min.js:7:21957
$@https://d2znry4lg8s0tq.cloudfront.net/angular/angular/1.3.15/angular.min.js:70:198
B@https://d2znry4lg8s0tq.cloudfront.net/angular/angular/1.3.15/angular.min.js:59:256
g@https://d2znry4lg8s0tq.cloudfront.net/angular/angular/1.3.15/angular.min.js:51:336
https://d2znry4lg8s0tq.cloudfront.net/angular/angular/1.3.15/angular.min.js:50:445
k@https://d2znry4lg8s0tq.cloudfront.net/angular/ui-router/0.2.13/angular-ui-router.min.js:7:21315
https://d2znry4lg8s0tq.cloudfront.net/angular/ui-router/0.2.13/angular-ui-router.min.js:7:21582
$broadcast@https://d2znry4lg8s0tq.cloudfront.net/angular/angular/1.3.15/angular.min.js:128:365
https://d2znry4lg8s0tq.cloudfront.net/angular/ui-router/0.2.13/angular-ui-router.min.js:7:17415
https://d2znry4lg8s0tq.cloudfront.net/angular/angular/1.3.15/angular.min.js:112:114
$digest@https://d2znry4lg8s0tq.cloudfront.net/angular/angular/1.3.15/angular.min.js:123:111
$apply@https://d2znry4lg8s0tq.cloudfront.net/angular/angular/1.3.15/angular.min.js:126:300
l@https://d2znry4lg8s0tq.cloudfront.net/angular/angular/1.3.15/angular.min.js:81:246
M@https://d2znry4lg8s0tq.cloudfront.net/angular/angular/1.3.15/angular.min.js:85:343
https://d2znry4lg8s0tq.cloudfront.net/angular/angular/1.3.15/angular.min.js:86:94
n@https://d2znry4lg8s0tq.cloudfront.net/angular/angular/1.3.15/angular.min.js:85:123
nrWrapper@https://www.nypl.org/locations/ottendorfer:7:11174
```

### CODE REVIEW

**Comment by EdwinGuzman** [comment]
Thanks for the PR! Really appreciate it. Right now this project is under low maintenance and so this was missed, sorry about that. This looks great and we can get this in but a few things to note:

- Can you point your PR to the `development` branch?
- Can you also make patch version updates where needed (e.g. `package.json`).
- You may have noticed that the stack is old and not many changes have been committed in a while. This app is going to be decommissioned for a new app soon. Hopefully, this won't be an issue then.

Thanks.

**Comment by dylex** [comment]
Like so? I also think I managed to do the build so included the dist files too.

**Comment by EdwinGuzman** [comment]
@gkallenberg what do you think?

**Comment by EdwinGuzman** [comment]
@dylex , thanks again for the PR. NYPL did a relaunch of the locations pages in Drupal https://www.nypl.org/locations and is currently working on a new finder/map feature.

I'll add a deprecated note to this repo soon. Sorry about this. As I'm not part of that team I wasn't aware of their release schedule or roadmap, but I'll let the team know about this issue.

**Pull request closed without merging**
