### PR TITLE
RENO-705 Add Google Optimize

### PR DESCRIPTION
**Pull request by gkallenberg**
Jira: https://jira.nypl.org/browse/RENO-705

Adds configuration and snippets for adding Google Optimize account to Analytics snippet. This is intended to replace Optimizely starting the week of December 9, 2019.

Moves the GA script to `<head>`

### CODE REVIEW

**Comment by EdwinGuzman** [comment]
Looks good but why are tests failing?

**Comment by gkallenberg** [comment]
There may have been a change to how the `xvfb` service is implemented for running tests. I've made the adjustment in `.travis.yml` which seems to have fixed the issue.

**Comment by gkallenberg** [comment]
@EdwinGuzman, I've updated the Travis script to call the test software (xvfb) correctly. Looks like the job is running properly now. I also added a Github branch protection in settings so that an approved review is required before merge is possible.

**Comment by EdwinGuzman** [comment]
@gkallenberg great, I actually don't know about that `xvfb` line and may be best to ask @holingpoon if that is still needed. But everything else looks good to me.

**Pull request merged**
