### PR TITLE
Www 404 line height

### PR DESCRIPTION
**Pull request by holingpoon**
One last override.

### CODE REVIEW

**Comment by ktp242** [comment]
Looks good! Just update the `RELEASES.md` :-)

**Comment by ktp242** [comment]
screen shot 2018-07-24 at 1 31 11 pm

I think the button's height is bigger than it on the other apps?

**Comment by holingpoon** [comment]
This is what the final product should look like
locations_production_em

**Comment by holingpoon** [comment]
@gkallenberg I'll make sure it is at least on Jira. I would like to put this on Github too, but should this be documented as an issue?

**Comment by holingpoon** [comment]
@gkallenberg Submitted issue #85

**Pull request merged**
