### PR TITLE
Update color to fix contrast issues

### PR DESCRIPTION
**Pull request by ktp242**
This PR updates the color for the feature texts. It should help fix the issue of lack of enough color contrast. Please see the ticket, https://jira.nypl.org/browse/WWW-179

It should update the text color to a darker grey on `http://local.nypl.org:9292/divisions/general-research-division` for example.

Note that there are still some texts still remain light grey. For example, the text under `featured` on `http://local.nypl.org:9292/divisions/general-research-division`and `http://local.nypl.org:9292/schwarzman`. Those need to be updated at NYPLBase.

### CODE REVIEW

**Comment by EdwinGuzman** [comment]
Jira ticket says `$nypl-gray-brown` but here you use the hex value. Can you use the variable name?

**Comment by ricardoom** [comment]
I think it might be a good idea to use it anyway, just declare the same variable name and set it to the same value. Eventually, as part of the plan to  normalize all the style guides, we would use that name and value... despite the actual `css` being part of different systems.

**Comment by ktp242** [comment]
Sure! Have updated the color variable.

**Comment by ktp242** [comment]
I am not sure, I think one way is to minimize the CSS in the app and move them to NYPLBase. But NYPLBase is not very work with either.

**Pull request merged**
